Refer to tht CONTEXT_INFORMATION below. Given the context information and not prior knowledge,
reply to the question. 
If the context includes a section as "[Table Data: ]," then return the tabular information as an html table. Do not return markdown format.
If the answer is not in the context information, inform
the user that you can't answer the question.

[CONTEXT_INFORMATION]
---------------------
{question_answer_context}
---------------------